apiVersion: batch/v1
kind: Job
metadata:
  name: linstor-storage-pool-init
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: linstor
          image: quay.io/piraeusdatastore/piraeus-server:v1.32.3
          imagePullPolicy: IfNotPresent
          env:
            - name: LS_CONTROLLERS
              value: https://linstor-controller.piraeus-datastore.svc:3371
          command:
            - /bin/sh
            - -c
            - |
              set -eu

              linstor_cmd() {
                linstor --disable-config \
                  --controllers "${LS_CONTROLLERS}" \
                  --cafile /etc/linstor/client/ca.crt \
                  --certfile /etc/linstor/client/tls.crt \
                  --keyfile /etc/linstor/client/tls.key \
                  --no-color --no-utf8 "$@"
              }

              nodes=""
              for i in $(seq 1 12); do
                nodes="$(linstor_cmd node list -p | awk -F'|' 'NR>2 && $2 ~ /node-/ {gsub(/^[ \t]+|[ \t]+$/, "", $2); gsub(/^[ \t]+|[ \t]+$/, "", $5); print $2 ":" $5}')" || true
                if [ -n "$nodes" ]; then
                  break
                fi
                echo "Waiting for LINSTOR controller... ($i/12)"
                sleep 5
              done
              if [ -z "$nodes" ]; then
                echo "No LINSTOR nodes found"
                exit 1
              fi

              devices="$(linstor_cmd physical-storage list -p | awk -F'|' 'NR>2 {col=$4; gsub(/^[ \t]+|[ \t]+$/, "", col); if (col == "") next; n=split(col, arr, /[ \t]+/); for (i=1;i<=n;i++){ if (arr[i] ~ /node-/) { match(arr[i], /(node-[^[]+)\[([^]]+)\]/, m); if (m[1] && m[2]) print m[1]":"m[2]; }}}')"

              offline=0
              for entry in $nodes; do
                node="${entry%%:*}"
                state="${entry##*:}"
                if [ "$state" != "Online" ]; then
                  echo "WARN: $node is $state; skipping"
                  offline=1
                  continue
                fi

                device_count="$(echo "$devices" | awk -F: -v n="$node" '$1==n {c++} END {print c+0}')"
                if [ "$device_count" -eq 0 ]; then
                  echo "WARN: No physical storage device found for $node; skipping"
                  continue
                fi
                if [ "$device_count" -gt 1 ]; then
                  echo "WARN: Multiple physical storage devices found for $node; skipping"
                  continue
                fi
                device="$(echo "$devices" | awk -F: -v n="$node" '$1==n {print $2; exit}')"

                pool_info="$(linstor_cmd storage-pool list -p --nodes "$node" | awk -F'|' 'NR>2 && $2 ~ /lvm-thick/ {gsub(/^[ \t]+|[ \t]+$/, "", $7); gsub(/^[ \t]+|[ \t]+$/, "", $9); print $7 ":" $9; exit}')"
                total="${pool_info%%:*}"
                total_compact="$(echo "$total" | tr -d '[:space:]')"
                pool_state="${pool_info##*:}"

                if [ -z "$pool_info" ]; then
                  if linstor_cmd resource list -p --nodes "$node" | awk -F'|' 'NR>2 && $2 ~ /[A-Za-z0-9]/ {found=1} END {exit found?0:1}'; then
                    echo "WARN: LINSTOR resources found on $node; skipping to avoid data loss"
                    continue
                  fi
                  echo "Creating device pool on $node (device=$device)"
                  linstor_cmd physical-storage create-device-pool lvm "$node" "$device" --pool-name linstor --storage-pool lvm-thick
                  continue
                fi

                if [ -z "$total_compact" ] || [ "$total_compact" = "0KiB" ] || [ "$total_compact" = "0B" ] || [ "$total_compact" = "0" ]; then
                  if linstor_cmd resource list -p --nodes "$node" | awk -F'|' 'NR>2 && $2 ~ /[A-Za-z0-9]/ {found=1} END {exit found?0:1}'; then
                    echo "WARN: LINSTOR resources found on $node; skipping to avoid data loss"
                    continue
                  fi
                  echo "Recreating empty pool on $node (state=$pool_state, total=$total)"
                  linstor_cmd storage-pool delete --nodes "$node" lvm-thick
                  linstor_cmd physical-storage create-device-pool lvm "$node" "$device" --pool-name linstor --storage-pool lvm-thick
                else
                  echo "Pool on $node has capacity ${total}; leaving as-is"
                fi
              done

              if [ "$offline" -ne 0 ]; then
                echo "WARN: Some nodes were offline; rerun once they are online."
              fi
          volumeMounts:
            - name: linstor-client-tls
              mountPath: /etc/linstor/client
              readOnly: true
      volumes:
        - name: linstor-client-tls
          secret:
            secretName: linstor-client-tls
