apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: linstor-csi-nfs
  namespace: monitoring
  labels:
    monitoring: default
spec:
  namespaceSelector:
    matchNames:
      - piraeus-datastore
  selector:
    matchLabels:
      app.kubernetes.io/component: linstor-csi-nfs
  endpoints:
    - port: metrics
      interval: 30s
