apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-exporter
  namespace: nvidia-dcgm-exporter
  labels:
    release: monitoring
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: nvidia-dcgm-exporter
    app.kubernetes.io/component: dcgm-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dcgm-exporter
      app.kubernetes.io/instance: nvidia-dcgm-exporter
      app.kubernetes.io/component: dcgm-exporter
  namespaceSelector:
    matchNames:
      - nvidia-dcgm-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
