apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/Nosmoht/homelab-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
