apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/node-feature-discovery/v0.17.2
patches:
  - target:
      kind: Namespace
      name: node-feature-discovery
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          pod-security.kubernetes.io/enforce: privileged
