apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-kube-prometheus-kube-etcd
  labels:
    app: kube-prometheus-stack-kube-etcd
    release: monitoring
spec:
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: kube-prometheus-stack-kube-etcd
      release: monitoring
  endpoints:
    - port: http-metrics
      scheme: http
