apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: monitoring
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: linstor-csi
  resources:
    requests:
      storage: 10Gi
