apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: LoadBalancer
  # TODO: Adjust to a reserved homelab MetalLB IP.
  loadBalancerIP: 10.0.0.70
  annotations:
    metallb.universe.tf/address-pool: homelab-monitoring
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      initContainers:
        - name: dashboards-loader
          image: curlimages/curl:8.10.1
          command:
            - /bin/sh
            - -c
            - |
              set -eu
              mkdir -p /var/lib/grafana/dashboards
              while read -r id name; do
                case "$id" in
                  ""|\#*) continue ;;
                esac
                curl -sL "https://grafana.com/api/dashboards/${id}/revisions/latest/download" \
                  -o "/var/lib/grafana/dashboards/${name}.json"
                sed -i 's/${DS_PROMETHEUS}/prometheus/g' "/var/lib/grafana/dashboards/${name}.json"
                case "$name" in
                  kube-state-metrics)
                    sed -i \
                      -e 's/${VAR_DATASOURCE}/prometheus/g' \
                      "/var/lib/grafana/dashboards/${name}.json"
                    ;;
                esac
              done < /etc/grafana/dashboards/dashboards.txt
          volumeMounts:
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: dashboards-config
              mountPath: /etc/grafana/dashboards
      containers:
        - name: grafana
          image: grafana/grafana:12.3.2
          ports:
            - name: http
              containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          env:
            - name: GF_SERVER_DOMAIN
              value: grafana.homelab.ntbc.io
            - name: GF_SERVER_ROOT_URL
              value: https://grafana.homelab.ntbc.io
            - name: GF_SECURITY_COOKIE_SECURE
              value: "true"
            - name: GF_SECURITY_COOKIE_SAMESITE
              value: lax
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-password
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: Dex
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              value: grafana
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana-oidc
                  key: client-secret
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: openid email profile groups
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              value: https://dex.homelab.ntbc.io/auth
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: https://dex.homelab.ntbc.io/token
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              value: https://dex.homelab.ntbc.io/userinfo
            - name: GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP
              value: "true"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "false"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard-providers
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: grafana-storage
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboard-providers
          configMap:
            name: grafana-dashboard-providers
        - name: dashboards-config
          configMap:
            name: grafana-dashboards
        - name: dashboards
          emptyDir: {}
