apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: cert-manager
    name: homelab
  project: homelab
  source:
    path: overlays/homelab/cert-manager
    repoURL: https://github.com/Nosmoht/homelab-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
