apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linstor
  namespace: argocd
spec:
  destination:
    namespace: piraeus-datastore
    name: homelab
  project: homelab
  source:
    path: overlays/homelab/linstor
    repoURL: https://github.com/Nosmoht/homelab-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true