apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: monitoring
    name: homelab
  project: homelab
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 81.6.1
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/overlays/homelab/monitoring/kps-values.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.6.0
      helm:
        releaseName: monitoring-alloy
        valueFiles:
          - $values/overlays/homelab/monitoring/alloy-values.yaml
    - repoURL: https://github.com/Nosmoht/homelab-apps.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Nosmoht/homelab-apps.git
      targetRevision: main
      path: overlays/homelab/monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipHooks=true
