apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-dcgm-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: nvidia-dcgm-exporter
    name: homelab
  project: homelab
  source:
    path: overlays/homelab/nvidia-dcgm-exporter
    repoURL: https://github.com/Nosmoht/homelab-apps.git
    targetRevision: main
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
