apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piraeus-operator
  namespace: argocd
spec:
  destination:
    namespace: piraeus-operator
    name: homelab
  project: homelab
  source:
    path: overlays/homelab/piraeus-operator
    repoURL: https://github.com/Nosmoht/homelab-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
