apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piraeus-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: piraeus-datastore
    name: homelab
  project: homelab
  source:
    path: overlays/homelab/piraeus-operator
    repoURL: https://github.com/Nosmoht/homelab-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
