apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.kubernetes.io/instance: homelab-apps
  name: homelab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Homelab
  destinationServiceAccounts:
    - defaultServiceAccount: homelab
      namespace: '*'
      server: https://10.0.0.10:6443
  destinations:
    - name: homelab
      namespace: '*'
      server: https://10.0.0.10:6443
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - https://github.com/Nosmoht/homelab-apps.git
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://nvidia.github.io/k8s-device-plugin
    - https://cloudnative-pg.github.io/charts
    - https://cloudnative-pg.github.io/charts*
    - https://ot-container-kit.github.io/helm-charts
    - https://ot-container-kit.github.io/helm-charts*
