apiVersion: v1
kind: Service
metadata:
  name: monitoring-kube-prometheus-kube-etcd
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-etcd
    release: monitoring
    jobLabel: kube-etcd
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 2381
      protocol: TCP
      targetPort: 2381
  type: ClusterIP
